## 📆 2024-05-20

### 🔔 스크럼

- 학습 목표 1 : Java 예외 처리
  <br/>

### 🚀 Today I Learned

#### | Java 예외

자바에서 오류는 `에러`와 `예외`로 구분

`예외`란, 자바 프로그램에서 실행 중에 발생할 수 있는 경미한 오류

- 사용자의 잘못된 조작이나 개발자의 코딩 로직의 실수로 인해 발생하는 프로그램의 오류
- 적절한 처리 모듈을 추가하여 발생한 문제를 복구할 수 있음

`에러`란, 자바 프로그램 밖에서 발생한 오류, 에플리케이션 내 코드로 해결할 수 없기에 복구가 불가능

- 메모리나 내부의 심각한 문제로 복구가 불가능한 오류

![예외와 에러](https://github.com/100-hours-a-week/erica-til/assets/81230764/6c644201-5fc2-4f99-918a-f374067243e6)

- NullPointerException  
   실제 변수에 저장된 객체가 null임에도 불구하고 객체의 멤버를 참조하는 경우
- ArrayIndexOutOfBoundsException  
   배열에서 배열의 첨자 범위를 벗어난 첨자 사용 (배열 인덱스 범위 밖을 참조하려는 경우)
- ArithmeticException  
   0으로 수를 나누려고 할 때 발생
- ArraysStoreException  
   배열에 잘못된 유형의 객체를 저장하려고 할 때 발생
- NegativeArraySizeException  
   배열의 크기를 음수로 지정하는 경우에 발생

#### | 예외 처리

프로그램 실행 중에 예외가 발생하면 예외 객체를 만들어 프로그램에 보내지는데, 이때 예외를 처리하는 모듈이 없으면 프로그램이 종료  
`예외처리`란, 예외가 발생하여 프로그램이 중단되지 않도록 하려면 예외를 처리하는 모듈

```
try {

  //예외가 발생될 수 있는 코드

} catch ( 예외클래스 이름 변수이름) {

  //예외 처리 모듈

} finally {

  //항상 실행되는 문장
  //catch가 발생해도 finally는 실행됨

}
```

- 예외 발생 가능성이 있는 문장들을 try { } 블록 안에 넣기
- 예외가 발생하면 복구나 처리를 위한 모듈은 catch { } 블록에서 구현
- finally { } 블록은 try 문이 실행되면 반드시 실행되는 문장 -> 예외 발생 상관없이 finally의 블록은 실행
- catch가 없는 try문은 의미가 없기 때문에 try를 쓸거면 catch는 반드시 작성할 것

### 🔥 오늘의 도전 과제와 해결 방법

- 도전 과제 1: java cli 프로그램에서 발생할 수 있는 예외 처리 해보기

### 🗨️ 오늘의 회고

<!--
- 오늘의 학습 경험에 대한 자유로운 생각이나 느낀 점을 기록합니다.
- 성공적인 점, 개선해야 할 점, 새롭게 시도하고 싶은 방법 등을 포함할 수 있습니다.-->

- 생각보다 코드에서 예외가 발생할 수 있는 점이 많아 앞으로 예외 처리에 신경을 많이 써야겠다고 생각했다.
